apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "rogue-cloud-server.fullname" . }}
  labels:
    app: {{ template "rogue-cloud-server.name" . }}
    chart: {{ template "rogue-cloud-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rogue-cloud-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rogue-cloud-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pv-claim
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: roguecloud
              value: "/rougecloud"
          ports:
            - name: https
              containerPort: 9443
              protocol: TCP
          volumeMounts:
          - mountPath: "/rougecloud"
            name: {{ .Release.Name }}-storage
          livenessProbe:
            httpGet:
              path: /{{ .Release.Name }}
              port: https
          readinessProbe:
            httpGet:
              path: /{{ .Release.Name }}
              port: https
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
